camunda.bpm.admin-user:
  id: demo
  password: demo


spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/camunda-postgres-database

#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    port: 587
#    username: eng.ahmedkhatab84@gmail.com
#    password: slftcdfibppbyikk
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
#      mail.smtp.starttls.required: true
